FROM golang:1.13 AS builder

WORKDIR /go/src/github.com/kubernetes-csi/external-snapshotter
COPY . .
RUN make build

LABEL maintainers="Kubernetes Authors"
LABEL description="CSI External Snapshotter Sidecar"

FROM registry.access.redhat.com/ubi8/ubi
COPY --from=builder /go/src/github.com/kubernetes-csi/external-snapshotter/bin/snapshot-controller /usr/bin/
ENTRYPOINT ["/usr/bin/snapshot-controller"]

